### ISSUE TITLE
Signature generation / validation not stable according to protobuf spec

### ISSUE THREAD

**Issue by ederuiter** [helium/oracles#363]
I am currently building [an integration](https://github.com/thisisdevelopment/helium-route-updater) with the iot config service in golang. During the implementation of the signed grpc requests I came across this note from the protobuf spec:

https://protobuf.dev/programming-guides/encoding/#implications

The way the signing / verification work atm is by emptying the signature field and re-serializing the message to generate / validate the signature. This is explicitly stated as not being guaranteed to be stable.
Currently it seems to work fine as I am able to sign messages in golang and use it the the config service written in rust .. but in order to prevent issues in the future I think it is a good idea to take a look at the current implementation.

**Comment by madninja** [comment]
Yeah, I remember seeing this a while back too.. Practically, all implementations appear to be serializing in tag order so we've not seen this be an issue across languages and in any of the transactions on chain. Thanks for pointing it out again though; we can't really change much here given how much legacy there already is.
