### ISSUE TITLE
[mobile-verifier] Add more heartbeats into MOBILE reward calculation

### ISSUE THREAD

**Issue by meowshka** [helium/oracles#53]
Currently we reward cells that heartbeated at least once in the 24h period. We should increase the number of heartbeats necessary for reward to promote consistent coverage. The requirements will be tightened with time, for now please use the following params: 
1. Reward period remains 24h
2. Heartbeats come every minute
3. Cell needs to heartbeat at least once in 1h to get 1 point (we take into account only 1 heartbeat in an hour vs 2 to compensate for potential issues with infra)
4. Max points that can be earned in 24h period is 24
5. Reward is given for cells with >=12 points.

Calculation example:
<img width="524" alt="Screen Shot 2022-12-01 at 1 57 17 PM" src="https://user-images.githubusercontent.com/5078844/205167632-4f7347a6-1b18-4912-94f0-42886913b24b.png">

**Comment by maplant** [comment]
@meowshka can we do this based on clock time? So for example if we have a heartbeat come in at 12:30, can we say that there was a valid heartbeat for the 12th hour? Rather than doing it based on when the previous heartbeat came in

**Comment by meowshka** [comment]
> @meowshka can we do this based on clock time? So for example if we have a heartbeat come in at 12:30, can we say that there was a valid heartbeat for the 12th hour? Rather than doing it based on when the previous heartbeat came in

Yes, we should do it on the clock time.
