### ISSUE TITLE
The speedtest average calculation should be unified for exported proto files and the rewarding

### ISSUE THREAD

**Issue by riobah** [helium/oracles#724]
The speedtest average calculation is not the same for speedtest average file generation (*avg of last 6 measurements*) and for the rewarding (*avg of last 6 measurements in the last 48 hours*). 

Users have the first one to see how their hotspot is doing, but the real result can be different. Thanks to the recent changes with the mobile reward share messages, now we can see what Oracles are actually seeing for the reward calculation. 

If there is no specific reason, can we have get_latest_speedtests_for_pubkey() and aggregate_epoch_speedtests() use the same approach?

**Comment by bbalser** [comment]
We now output a new speedtest average that is used during reward calculation.
