### ISSUE TITLE
mismatch for SP boosted hexes with rate 1.0 and HIP103 implementation

### ISSUE THREAD

**Issue by riobah** [helium/oracles#763]
If the SP decides to boost some Mexico hexes with 1.0 rate, HIP103 says we should reward them. Checking the code I could not be sure if we'd actually do it.

[HIP103](https://github.com/helium/HIP/blob/main/0103-oracle-hex-boosting.md): 
> *if a res12 hex is boosted by a Service Provider of ≥1, the Oracle Multiplier will automatically be 1.00X*

code:
```
                let oracle_multiplier = if boost_multiplier > 1 {
                    dec!(1.0)
                } else {
                    urbanization_multiplier(cl.urbanized)
                };
```

`>` vs `≥`

**Comment by bbalser** [comment]
https://github.com/helium/oracles/pull/764 should have solve this problem.
