### ISSUE TITLE
Grafana dashboards for Oracles

### ISSUE THREAD

**Issue by dpezely** [helium/oracles#78]
Create first iteration of Grafana dashboards for Oracles

- There will be several learning curves with this task:
  + Prometheus semantics
  + Grafana expressions, builder UI and creating/modifying Dashboards
- Modelling new dashboards somewhat off of `router-prod`
  + Exported JSON seems more comprehensive than version in router git repo
  + Beware that router uses legacy "Grafana alerting" yet new ones should use v9.0 or higher
- Use metrics collected from 2 hosts via Prometheus
- Alarms beyond flatline detection will be a future effort, because we'll want to watch and discover thresholds
- See also: (thanks Jon!)
  + https://promlabs.com/promql-cheat-sheet/
  + https://prometheus.io/docs/prometheus/latest/querying/basics/
  + https://grafana.com/docs/grafana/latest/alerting/

Tasks / new dashboards:
- [x] speed test
    - ~~code~~
    - ~~data~~
    - [x] plot
- [x] heartbeat
    - ~~code~~
    - ~~data~~
    - [x] plot
- [ ] gPRC connections
    - [x] code
    - [ ] data
    - [ ] plot
- [x] emission
    - ~~code~~
    - ~~data~~
    - [x] plot
- [x] ~~last reward height of blockchain~~ (already existed)
- [x] processed files
    - [x] code
    - [x] data
    - [x] plot
- [ ] connection count
    - [x] code
    - [ ] data
    - [ ] plot
- [ ] request durations
    - [x] code
    - [ ] data
    - [ ] plot
- [ ] Track when any of those sustains a flatline, but trigger an alarm only once per group per host

code: https://github.com/helium/oracles/pull/94
plots: https://dashboard.helium.com/d/p0fykbVVk/oracles-x?orgId=1&from=now-30d&to=now&refresh=5s

**Comment by dpezely** [comment]
Dashboards exist for mainnet and devnet, which may be extended once a new chart has been exercised in an Explore sandbox.  Some items in the description already exist.

Additional resources for useful graphs and understanding existing `router-prod` dashboard expressions:
- https://prometheus.io/docs/practices/histograms/
- https://www.robustperception.io/rate-then-sum-never-sum-then-rate/

Note that Prometheus performs bucketing, quantiles (e.g., quartiles, percentiles), etc., so approach can differ compared to other monitoring and dashboard systems.

**Comment by dpezely** [comment]
Attempting to use `router-prod` Grafana dashboard as a reference for making new charts leads to an impedance mismatch due to different types of metrics collected.  Where router makes heavy use of Labels in Prometheus, there are none yet with Oracles.

Some metrics available in Prometheus for Oracles still have no data or constant stream of zeros.  That hinders experimentation for finding an adequate charting recipe.

**Comment by madninja** [comment]
> Attempting to use `router-prod` Grafana dashboard as a reference for making new charts leads to an impedance mismatch due to different types of metrics collected. Where router makes heavy use of Labels in Prometheus, there are none yet with Oracles.
> 
> Some metrics available in Prometheus for Oracles still have no data or constant stream of zeros. That hinders experimentation for finding an adequate charting recipe.

1. time to find out why those are zeros! 
2. do we need to add labels to the metrics used in oracles to make it easier to slice and dice?

**Comment by dpezely** [comment]
> 1.  time to find out why those are zeros!

Not all metrics are zeroed, so there's no infrastructure or connection issue.  For now, it seems we have too little data flowing from too few metrics, since the Rust code makes only light use of reporting metrics.  As I'm reviewing the various PRs, I hope to have meaningful recommendations for what & where to add metrics but still getting my head around all the various members within `oracles` repo.  But don't want to get pulled in too many directions.

> 2.  do we need to add labels to the metrics used in oracles to make it easier to slice and dice?

Not yet.  For `router` labels were for things like classifying reasons for packet rejection.

**Comment by dpezely** [comment]
For monitoring traffic and health of handling that traffic, let's emit via prometheus:
- Count of txn/submits per input file ingested; e.g., `poc_iot_injector_txn_total`
- Label each with `status=ok` or simple reason for failure; e.g., `status=unexpected-eof`
- existence of that metric also gives timestamp of opening new input, which we can track

Tracking duration of handling *each* item of input probably not as useful
as for websites with 2s requirements.
However, some indication of timeliness or "aliveness"
helps track sluggish services and abuse-detection.

while items above track how much goes in, how much goes out
let's track how much time/work gets spent in between:
- Gauge exercising/allocating key resources: `..._cache_miss_total` (i.e., wallet pubkey lookups)
- we already have `reward_server_emission_duration`, `reward_server_processed_files` and `status_server_get_gateway_duration`
- "To pick between counter and gauge, there is a simple rule of thumb:
if the value can go down (other than reset to 0), it is a **gauge**."

Definitely requires discussion:
- Gauge overall rewards & debits: `..._rewards`, `..._debits` per input file
  + or a proxy for number of gateway wallets touched, etc.

**Comment by dpezely** [comment]
Notes from [Learning Grafana + Prometheus](https://gist.github.com/dpezely/771eebcfca9c9fb167d46d62a5555ea0) will be cleaned and published somewhere relevant but stashed as a Gist while in rough outline form.
