### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by wootteck** [helium/oracles#885]
Hi,

I hope this message finds you well. 

I am reaching out to inquire about any potential vacancies at your company. 
With experience at Firestarter and Autonomy Network, I have developed high-performance smart contracts and backend services on the Solana network, utilizing Rust to enhance trading operations and security. 
My background also includes optimizing transaction efficiency and implementing advanced security measures. 
Is there any opening developer vacancy? If so, I look forward to discuss further.

Please have a look at the links below
https://flowcv.com/resume/649rct92t6
https://www.linkedin.com/in/ngajicup

**Comment by madninja** [comment]
Please do not spam a code repository with job requets
